### ISSUE TITLE
.lowerCaseValues strips punctuation (and other things)

### ISSUE THREAD

**Issue by RulerOf** [MIRTAHAALI/json-case-convertor#4] opened 2022-09-28 02:42 UTC
Hi, thanks for the module.

Tried to use it but hit a showstopper:

```node
> jcc.lowerCaseValues({"key":"value.hErE"})
{ key: 'value h er e' }
> 
```

Using node:
```
╰─❯ node -v
v16.14.0
```

**Comment by MIRTAHAALI** [comment] 2022-09-28 17:29
Hi, Thanks for raising the issue. The issue is now fixed and available on latest npm package of json-case-convertor that is 1.4.0

**Comment by MIRTAHAALI** [comment] 2022-09-28 17:29
Hi, Thanks for raising the issue. The issue is now fixed and available on latest npm package of json-case-convertor that is 1.4.0

**Closed as completed by MIRTAHAALI** 2022-09-28 17:29 UTC
